---
title: "ARIMA"
author: "Jackson Dial"
date: '2023-04-13'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("forecast")
library(dplyr)
library(forecast)
library(ggplot2)
library(beepr)
```

The purpose of this document is to create an ARIMA (Auto-Regressive Integrated Moving Average) model.



```{r}
# create time series object
date <- as.Date("1990-04-30")

# Extract the week of the year
week <- format(date, "%U")
week

all_data <- features_train %>% left_join(labels_train, by = c("year", "weekofyear", "city"))
```

```{r both cities}
ggplot(all_data, aes(x = week_start_date, y = total_cases, col = as.factor(city)))+
  geom_line()+
  labs(x = "Time",
       y = "Total Cases",
       col = "City",
       title = "Cases Over Time",
       subtitle = "Both Cities")+
  scale_color_manual(values = c("dodgerblue", "forestgreen"),
    labels = c("Iquitos", "San Juan"))
```

```{r just iquitos}
all_data %>% filter(city == "iq") %>% 
  ggplot(aes(x = week_start_date, y = total_cases, col = city))+
  geom_line()+
  labs(x = "Time",
       y = "Total Cases",
       title = "Cases Over Time",
       subtitle = "Only Iquitos")+
  scale_color_manual(values = "dodgerblue")+
  theme(legend.position = "none")
```

## Iquitos

```{r}
iq_all <- all_data %>% filter(city == "iq")
iq_ts_obj <- ts(iq_all$total_cases, frequency = 52, start = c(2000, 26))
iq_all_features <- features_train %>% filter(city == "iq") %>% 
  select(ndvi_ne:station_precip_mm) %>% 
  subset(select = -c(precipitation_amt_mm))

iq_arima <- auto.arima(iq_ts_obj,xreg = as.matrix(iq_all_features))
summary(iq_arima)
```

```{r}
iq_residuals <- residuals(iq_arima)
par(mfrow = c(2,2))

# Plot the residuals over time
plot(iq_residuals, type = "l", main = "Residuals of ARIMA(0,1,2) Model")

# Create a histogram of the residuals
hist(iq_residuals, breaks = 10, main = "Histogram of Residuals")

# Create a density plot of the residuals
plot(density(iq_residuals), main = "Density Plot of Residuals")

# Create a Q-Q plot of the residuals
qqnorm(iq_residuals)
qqline(iq_residuals)

```


```{r iquitos preds}
test_iq_date <- features_test %>% filter(city == "iq") %>% select(week_start_date)
iq_test <- features_test %>% filter(city == "iq")

iq_pred_date <- cbind(test_iq_date, iq_preds)

iq_test <- features_test %>% filter(city == "iq")%>% 
  select(ndvi_ne:station_precip_mm) %>% 
  subset(select = -c(precipitation_amt_mm))
iq_preds <- forecast(iq_arima, h = 260, xreg = as.matrix(iq_test) )

iq_pred_date <- cbind(test_iq_date, iq_preds)

ggplot(iq_pred_date, aes(x = week_start_date, y = `Point Forecast`))+
  geom_line()
```

## San Juan


```{r}
sj_all <- all_data %>% filter(city == "sj")
sj_ts_obj <- ts(sj_all$total_cases, frequency = 52, start = c(1990, 18))
# sj_arima <- auto.arima(sj_ts_obj)
sj_all_features <- features_train %>% filter(city == "sj") %>% 
  select(ndvi_ne:station_precip_mm) %>% 
  subset(select = -c(precipitation_amt_mm))

sj_arima <- auto.arima(sj_ts_obj,xreg = as.matrix(sj_all_features))
summary(sj_arima)
```

```{r}
sj_residuals <- residuals(sj_arima)

par(mfrow = c(2,2))
# Plot the residuals over time
plot(sj_residuals, type = "l", main = "Residuals of ARIMA(1,1,1) Model")

# Create a histogram of the residuals
hist(sj_residuals, breaks = 10, main = "Histogram of Residuals")

# Create a density plot of the residuals
plot(density(sj_residuals), main = "Density Plot of Residuals")

# Create a Q-Q plot of the residuals
qqnorm(sj_residuals)
qqline(sj_residuals)
```

## Predictions

```{r}
# how many weeks do we want to predict for iquitos?
features_test %>% 
  filter(city == "iq") %>% 
  nrow()
#156 for iquitos

features_test %>% 
  filter(city == "sj") %>% 
  nrow()
#260 for san juan
```

```{r sanjuan preds}
summary(sj_test)

test_sj_date <- features_test %>% filter(city == "sj") %>% select(week_start_date)
sj_test <- features_test %>% filter(city == "sj")%>% 
  select(ndvi_ne:station_precip_mm) %>% 
  subset(select = -c(precipitation_amt_mm))
sj_preds <- forecast(sj_arima, h = 260, xreg = as.matrix(sj_test) )

sj_pred_date <- cbind(test_sj_date, sj_preds)

ggplot(sj_pred_date, aes(x = week_start_date, y = `Point Forecast`))+
  geom_line()
```

